# nodeJS Image for Linux with local folder /app containing package.json
FROM  node:18-alpine
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm install --production

COPY . .

CMD [ "node", "server.js" ]FROM alpine

